#!/usr/bin/env bash
# mkdisk.sh <kernel> <initramfs.cpio.gz> <out.raw> [kernel cmdline...]
#
# Builds a UEFI-bootable GPT disk image without root privileges (everything
# runs in an x86-64 Alpine container, for GRUB's x86_64-efi modules):
#
#   GPT
#   └─ partition 1 (EF00, FAT32, whole disk minus headers)
#        EFI/BOOT/BOOTX64.EFI   GRUB standalone with embedded grub.cfg
#        kernel                 Asterinas multiboot2 ELF, or Linux bzImage
#        initramfs.cpio.gz
#
# KERNEL_KIND=asterinas (default) boots with `multiboot2` + `module2`;
# KERNEL_KIND=linux boots with `linux` + `initrd`.
# DISK_MB (default 96) sets the image size, ESP_MB (default DISK_MB-2) the
# size of the single partition. `make ami` uses DISK_MB=1024 so the GPT matches
# EBS's 1 GiB minimum volume; the unused tail is all zeros and never uploaded.
set -euo pipefail
KERNEL=$1; INITRAMFS=$2; OUT=$3; shift 3
CMDLINE=${*:-"console=ttyS0 earlycon loglevel=error uniapp.mode=app"}
KIND=${KERNEL_KIND:-asterinas}
DISK_MB=${DISK_MB:-96}
ESP_MB=${ESP_MB:-$((DISK_MB - 2))}

# Work dir under the output dir: macOS mktemp paths are not shared with the Docker VM.
WORK=$(cd "$(dirname "$OUT")" && pwd)/.mkdisk; rm -rf "$WORK"; trap 'rm -rf "$WORK"' EXIT
mkdir -p "$WORK/esp/EFI/BOOT" "$(dirname "$OUT")"
cp "$KERNEL" "$WORK/esp/kernel"
cp "$INITRAMFS" "$WORK/esp/initramfs.cpio.gz"

if [ "$KIND" = asterinas ]; then
  # OSDK rewrites e_machine to EM_386 so QEMU's -kernel accepts the 64-bit
  # multiboot ELF; GRUB's loader insists on EM_X86_64. Restore it.
  python3 - "$WORK/esp/kernel" <<'PY'
import sys; p=sys.argv[1]; b=bytearray(open(p,'rb').read())
assert b[:4]==b'\x7fELF'
if b[18]==3 and b[19]==0: b[18]=62; open(p,'wb').write(b); print("mkdisk: restored e_machine=EM_X86_64")
PY
  BOOT_CMDS="    multiboot2 /kernel $CMDLINE
    module2 --nounzip /initramfs.cpio.gz"
else
  BOOT_CMDS="    linux /kernel $CMDLINE
    initrd /initramfs.cpio.gz"
fi

cat > "$WORK/grub.cfg" <<EOF
# generated by scripts/mkdisk.sh
serial --unit=0 --speed=115200
terminal_input serial console
terminal_output serial console
# grub-mkstandalone sets \$root to its embedded memdisk; switch to the ESP.
search --no-floppy --set=root --label ESP
set timeout=0
set default=0
menuentry 'elixir_unikernel ($KIND)' {
$BOOT_CMDS
    boot
}
EOF

docker run --rm --platform linux/amd64 -v "$WORK":/w -v "$(cd "$(dirname "$OUT")" && pwd)":/out alpine:3.22 sh -ec '
  apk add --no-cache grub grub-efi mtools sgdisk dosfstools >/dev/null 2>&1
  # GRUB standalone EFI binary with the config embedded.
  grub-mkstandalone -O x86_64-efi -o /w/esp/EFI/BOOT/BOOTX64.EFI \
     --modules="part_gpt fat multiboot2 linux normal configfile serial terminal echo ls cat search search_label all_video gfxterm" \
     --locales="" --themes="" --fonts="" \
     "boot/grub/grub.cfg=/w/grub.cfg"
  ls -l /w/esp/EFI/BOOT/BOOTX64.EFI
  OUT=/out/'"$(basename "$OUT")"'
  rm -f "$OUT"; truncate -s '"$DISK_MB"'M "$OUT"
  sgdisk -Z "$OUT" >/dev/null
  # partition 1 starts at sector 2048 = 1 MiB and is ESP_MB long
  sgdisk -n 1:2048:+'"$ESP_MB"'M -t 1:ef00 -c 1:ESP "$OUT" >/dev/null
  mkfs.vfat -F 32 -n ESP -C /w/esp.img $(( '"$ESP_MB"' * 1024 )) >/dev/null
  mcopy -i /w/esp.img -s /w/esp/* ::
  dd if=/w/esp.img of="$OUT" bs=1M seek=1 conv=notrunc status=none
  sgdisk -p "$OUT" | tail -3
  mdir -i "$OUT"@@1M -/ :: | grep -vE "^\s*$|Volume|Directory" | head -12
'
ls -l "$OUT"
